name: presentation
description: Saglac.io demo project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.1.4
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/austinparker.jpg
    - assets/joellord.jpg
    - assets/ophelie.jpg
    - assets/damien.jpg
    - assets/joel.jpg
    - assets/juliensamuel.jpg
    - assets/micael.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.ttf
        - asset: assets/Poppins-ExtraBold.ttf
          weight: 700
